###
GET http://localhost:3000/products


###
GET http://localhost:3000/products/citron

###
POST http://localhost:3000/products 
content-type: application/json

{
    "name": "citron",
    "quantity": 17
}

###
DELETE http://localhost:3000/products/citron?quantity=5 


